adminPassword: admin


datasources:

  datasources.yaml:

    apiVersion: 1

    datasources:

    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true



dashboards:

  default:


    kubernetes-cluster:

      gnetId: 315
      datasource: Prometheus


    nginx-dashboard:

      gnetId: 12708
      datasource: Prometheus


    node-exporter:

      gnetId: 1860
      datasource: Prometheus